// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oruarfhhzpqsdioiexrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ydWFyZmhoenBxc2Rpb2lleHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwMjg1MjIsImV4cCI6MjA1MDYwNDUyMn0.SInAGuXz9zGdCrrfmXOpFEaToBo3C8bDj50zljI5ceU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);